"""Add fecha column to tasks

Revision ID: d88425d662d0
Revises: ad9ac91a3769
Create Date: 2025-05-23 14:11:27.380929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88425d662d0'
down_revision: Union[str, None] = 'ad9ac91a3769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('fecha', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'fecha')
    # ### end Alembic commands ###
